version: "3.8"

services:
  task-get-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-get-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-get-video-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-extract-sound:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-extract-sound
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-extract-sound-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-generate-subtitle:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-generate-subtitle
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-generate-subtitle-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-transform-subtitle:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-transform-subtitle
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-transform-subtitle-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-resize-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-resize-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-resize-video-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-embed-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-embed-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-embed-video-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-chunk-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-chunk-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-chunk-video-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

  task-resume-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-resume-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: ${PROJECT_NAME}-task-resume-video-dev
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - substream-network

volumes:
  cargo-cache:
  target-cache:

networks:
  substream-network:
    external: true
